use ipu_exchange::{
    PLAN_WORDS, SANS_INACTIVE_INSTRUCTION, SYNC_SUPERVISOR_INSTRUCTION, encode_add_m_immediate,
    encode_br_m, encode_brz_m_immediate, encode_call_m_immediate, encode_ld32_m_immediate,
    encode_put_special_m, encode_setzi_m, encode_shl_m_immediate, encode_st32_m_immediate,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub mod graph;
pub mod low;
pub mod mid;
mod package;
pub use graph::{
    ComputeGraph, GraphError, GraphInput, GraphInputKind, GraphResult, Operation, OperationId,
    OperationKind, Region, RegionBuilder, Repeat, RepeatArguments, TensorShape, ValueId,
    ValueSequence, ValueSequenceId,
};
pub use low::{
    ExchangePhase, ExchangePhaseId, KernelOperand, KernelRun, LogicalExchange, LowInput, LowKernel,
    LowLoweringConfig, LowLoweringError, LowLoweringResult, LowProgram, LowShard, LowShardId,
    LowValue, RepeatCarried, RepeatInvariant, RepeatIterated, RepeatRun, ShardDefinition,
    ShardExtent, TileWork, TileWorkList, lower_to_tiles,
};
pub use mid::{
    AccumulationPrecision, AmpOrder, AxisTiling, CostModel, ElementOrder, KernelCandidate,
    KernelRequirements, Layout, LayoutError, LoweringConfig, LoweringError, LoweringResult,
    MemoryClass, MemoryOperand, MemoryRelation, MidGraph, MidInput, MidKernel, MidOperation,
    MidOperationKind, MidRegion, MidRepeat, MidValue, MidValueId, OperandRequirement,
    OutputAliasing, Padding, Precision, TensorAxis, TensorFormat, TensorTiling, TensorType,
    ToyCostModel, lower,
};
pub use package::{PackageBuildError, PackageBuildResult, PackageConfig, build_package};

const INCOMING_DBASE: u8 = 0xa4;
const INCOMING_DCOUNT: u8 = 0xa6;
const INCOMING_SBASE: u8 = 0xa7;
const FIRST_INPUT_REGISTER: u8 = 3;
const LAST_VALUE_REGISTER: u8 = 9;

pub const WORKER_BARRIER_SYMBOL: &str = "ipu_stack_static_worker_barrier";
pub const COMPLETE_SYMBOL: &str = "ipu_stack_static_complete";
pub const HOST_RUN_SYMBOL: &str = "ipu_stack_static_host_run";
pub const REPEAT_CALL_SYMBOL: &str = "ipu_stack_static_repeat_call";
pub const SAMPLE_CYCLE_SYMBOL: &str = "ipu_stack_static_sample_cycle";
pub const RUNTIME_ENTRY_SYMBOL: &str = "ipu_stack_static_start";
pub const PROGRAM_ADDRESS_SYMBOL: &str = "ipu_stack_static_program";
pub const WORKER_SYNC_CONTEXT_SYMBOL: &str = "ipu_stack_static_worker_sync_context";
pub const WORKER_STACK_BASE_SYMBOL: &str = "ipu_stack_static_worker_stack_base";
pub const PRNG_SEED_SYMBOL: &str = "ipu_stack_static_prng_seed";
pub const HOST_STAGING_SYMBOL: &str = "ipu_stack_static_host_staging";
pub const COMPLETION_ADDRESS_SYMBOL: &str = "ipu_stack_static_completion";

#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    #[error("exchange encoding failed: {0}")]
    Exchange(#[from] ipu_exchange::ExchangeError),
    #[error("invalid tile program: {0}")]
    Invalid(String),
}

pub type Result<T> = std::result::Result<T, CodegenError>;

/// A fully resolved program for one logical tile.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TileProgram {
    pub tile: u16,
    pub steps: Vec<TileStep>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TileStep {
    Exchange(ExchangeStep),
    Compute(ComputeStep),
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExchangeStep {
    /// Address at which `row` will be placed by the package builder.
    pub address: u32,
    /// Complete exchange row generated by `ipu-exchange`.
    pub row: Vec<u32>,
    #[serde(default)]
    pub profile: StepProfile,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ComputeStep {
    /// Exact linked kernel symbol; no naming convention is applied.
    pub symbol: String,
    pub output_address: u32,
    pub input_addresses: Vec<u32>,
    pub arguments: Vec<u32>,
    #[serde(default)]
    pub profile: StepProfile,
}

/// Optional explicit cycle-counter destinations around a step.
///
/// The addresses belong to caller-managed tile memory.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct StepProfile {
    pub before: Option<u32>,
    pub after: Option<u32>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct HostPhase {
    pub address: u32,
    pub active: bool,
    pub run_table: Option<u32>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct HostProgram {
    pub initialize: Vec<HostPhase>,
    pub inputs: Vec<HostPhase>,
    pub outputs: Vec<HostPhase>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CodegenOptions {
    /// Address where the first emitted byte will be placed.
    pub code_address: u32,
    pub invocations: u32,
    pub initial_profile_address: Option<u32>,
    pub final_profile_address: Option<u32>,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            code_address: 0,
            invocations: 1,
            initial_profile_address: None,
            final_profile_address: None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedProgram {
    pub bytes: Vec<u8>,
    /// Exchange data retained verbatim for explicit package placement.
    pub exchange_rows: Vec<PlacedExchangeRow>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PlacedExchangeRow {
    pub address: u32,
    pub words: Vec<u32>,
}

pub fn emit(
    program: &TileProgram,
    symbols: &BTreeMap<String, u32>,
    host: &HostProgram,
    options: &CodegenOptions,
) -> Result<GeneratedProgram> {
    if options.invocations == 0 {
        return Err(invalid("invocation count must be nonzero"));
    }
    validate(program)?;

    let complete = symbol(symbols, COMPLETE_SYMBOL)?;
    let mut code = TileCode::default();
    emit_host_phases(&mut code, symbols, &host.initialize)?;

    if options.invocations > 1 {
        code.add_immediate(11, 11, -8)?;
        code.setzi(0, options.invocations)?;
        code.st32(0, 11, 15, 0)?;
    }
    let invocation_start = code.address(options.code_address)?;
    emit_host_phases(&mut code, symbols, &host.inputs)?;

    if program.steps.iter().any(active_exchange) {
        code.put_special(INCOMING_SBASE, 15)?;
        code.put_special(INCOMING_DBASE, 15)?;
        code.setzi(8, 1)?;
        code.put_special(INCOMING_DCOUNT, 8)?;
    }
    if let Some(address) = options.initial_profile_address {
        emit_cycle_sample(&mut code, symbols, address)?;
    }

    let worker_barrier = program
        .steps
        .iter()
        .any(active_exchange)
        .then(|| symbol(symbols, WORKER_BARRIER_SYMBOL))
        .transpose()?;
    let mut exchange_rows = Vec::new();
    for step in &program.steps {
        match step {
            TileStep::Exchange(exchange) => {
                if let Some(address) = exchange.profile.before {
                    emit_cycle_sample(&mut code, symbols, address)?;
                }
                code.instruction(SYNC_SUPERVISOR_INSTRUCTION);
                let active = exchange.row[0] != SANS_INACTIVE_INSTRUCTION;
                if active {
                    code.call(worker_barrier.expect("active exchange has barrier"), 7)?;
                }
                code.call(exchange.address, 10)?;
                if let Some(address) = exchange.profile.after {
                    emit_cycle_sample(&mut code, symbols, address)?;
                }
                exchange_rows.push(PlacedExchangeRow {
                    address: exchange.address,
                    words: exchange.row.clone(),
                });
            }
            TileStep::Compute(compute) => {
                if let Some(address) = compute.profile.before {
                    emit_cycle_sample(&mut code, symbols, address)?;
                }
                emit_compute(&mut code, program.tile, compute, symbols)?;
                if let Some(address) = compute.profile.after {
                    emit_cycle_sample(&mut code, symbols, address)?;
                }
            }
        }
    }

    if let Some(address) = options.final_profile_address {
        emit_cycle_sample(&mut code, symbols, address)?;
    }
    emit_host_phases(&mut code, symbols, &host.outputs)?;
    if options.invocations > 1 {
        code.ld32(0, 11, 15, 0)?;
        code.add_immediate(0, 0, -1)?;
        code.st32(0, 11, 15, 0)?;
        let done_branch = code.words.len();
        code.brz(0, 0)?;
        code.jump(invocation_start)?;
        let done = code.address(options.code_address)?;
        code.words[done_branch] = encode_brz_m_immediate(0, done)?;
        code.add_immediate(11, 11, 8)?;
    }
    code.jump(complete)?;

    Ok(GeneratedProgram {
        bytes: code.words.into_iter().flat_map(u32::to_le_bytes).collect(),
        exchange_rows,
    })
}

fn validate(program: &TileProgram) -> Result<()> {
    for step in &program.steps {
        match step {
            TileStep::Exchange(exchange) => {
                if exchange.address & 3 != 0 {
                    return Err(invalid("exchange row address is not word aligned"));
                }
                if exchange.row.len() != PLAN_WORDS {
                    return Err(invalid(format!(
                        "exchange row has {} words, expected {PLAN_WORDS}",
                        exchange.row.len()
                    )));
                }
            }
            TileStep::Compute(compute) => {
                if compute.symbol.is_empty() {
                    return Err(invalid("compute symbol is empty"));
                }
                let values = compute.input_addresses.len() + compute.arguments.len();
                let available = usize::from(LAST_VALUE_REGISTER - FIRST_INPUT_REGISTER + 1);
                if compute.input_addresses.is_empty() || values > available {
                    return Err(invalid(format!(
                        "kernel {} needs {values} input/argument registers; 1..={available} are supported",
                        compute.symbol
                    )));
                }
            }
        }
    }
    Ok(())
}

fn active_exchange(step: &TileStep) -> bool {
    matches!(
        step,
        TileStep::Exchange(exchange)
            if exchange.row.first() != Some(&SANS_INACTIVE_INSTRUCTION)
    )
}

fn emit_compute(
    code: &mut TileCode,
    tile: u16,
    compute: &ComputeStep,
    symbols: &BTreeMap<String, u32>,
) -> Result<()> {
    let argument_base = FIRST_INPUT_REGISTER
        .checked_add(
            u8::try_from(compute.input_addresses.len())
                .map_err(|_| invalid("kernel input count exceeds u8"))?,
        )
        .ok_or_else(|| invalid("kernel input register overflow"))?;
    code.setzi(2, compute.output_address)?;
    for (index, &address) in compute.input_addresses.iter().enumerate() {
        code.setzi(
            FIRST_INPUT_REGISTER
                + u8::try_from(index).map_err(|_| invalid("kernel input count exceeds u8"))?,
            address,
        )?;
    }
    for (index, &argument) in compute.arguments.iter().enumerate() {
        code.setzi(
            argument_base
                + u8::try_from(index).map_err(|_| invalid("kernel argument count exceeds u8"))?,
            argument,
        )?;
    }
    let kernel = symbols.get(&compute.symbol).copied().ok_or_else(|| {
        invalid(format!(
            "tile {tile} references missing kernel symbol {}",
            compute.symbol
        ))
    })?;
    code.call(kernel, 10)
}

fn emit_host_phases(
    code: &mut TileCode,
    symbols: &BTreeMap<String, u32>,
    phases: &[HostPhase],
) -> Result<()> {
    if phases.is_empty() {
        return Ok(());
    }
    let repeat_call = phases
        .iter()
        .any(|phase| !phase.active)
        .then(|| symbol(symbols, REPEAT_CALL_SYMBOL))
        .transpose()?;
    let host_run = phases
        .iter()
        .any(|phase| phase.active)
        .then(|| symbol(symbols, HOST_RUN_SYMBOL))
        .transpose()?;
    let mut index = 0;
    while index < phases.len() {
        let start = index;
        if phases[start].active {
            while index < phases.len()
                && phases[index].active
                && phases[index].address == phases[start].address
            {
                index += 1;
            }
            code.setzi(
                2,
                u32::try_from(index - start).map_err(|_| invalid("host run overflow"))?,
            )?;
            code.setzi(
                3,
                phases[start]
                    .run_table
                    .ok_or_else(|| invalid("active host phase has no run table"))?,
            )?;
            code.setzi(4, phases[start].address)?;
            code.call(host_run.expect("active host phase has host runner"), 9)?;
        } else {
            while index < phases.len() && !phases[index].active {
                index += 1;
            }
            code.setzi(
                2,
                u32::try_from(index - start).map_err(|_| invalid("host run overflow"))?,
            )?;
            code.setzi(3, phases[start].address)?;
            code.call(
                repeat_call.expect("inactive host phase has repeat helper"),
                9,
            )?;
        }
    }
    Ok(())
}

fn emit_cycle_sample(
    code: &mut TileCode,
    symbols: &BTreeMap<String, u32>,
    address: u32,
) -> Result<()> {
    code.setzi(2, address)?;
    code.call(symbol(symbols, SAMPLE_CYCLE_SYMBOL)?, 10)
}

fn symbol(symbols: &BTreeMap<String, u32>, name: &str) -> Result<u32> {
    symbols
        .get(name)
        .copied()
        .ok_or_else(|| invalid(format!("missing runtime symbol {name}")))
}

fn invalid(message: impl Into<String>) -> CodegenError {
    CodegenError::Invalid(message.into())
}

#[derive(Default)]
struct TileCode {
    words: Vec<u32>,
}

impl TileCode {
    fn address(&self, base: u32) -> Result<u32> {
        base.checked_add(
            u32::try_from(self.words.len())
                .map_err(|_| invalid("generated code exceeds u32"))?
                .checked_mul(4)
                .ok_or_else(|| invalid("generated code size overflow"))?,
        )
        .ok_or_else(|| invalid("generated code address overflow"))
    }

    fn setzi(&mut self, register: u8, immediate: u32) -> Result<()> {
        if immediate < 1 << 20 {
            self.words.push(encode_setzi_m(register, immediate)?);
        } else {
            self.words.push(encode_setzi_m(register, immediate >> 12)?);
            self.words
                .push(encode_shl_m_immediate(register, register, 12)?);
            self.words.push(encode_add_m_immediate(
                register,
                register,
                i32::from((immediate & 0xfff) as u16),
            )?);
        }
        Ok(())
    }

    fn instruction(&mut self, instruction: u32) {
        self.words.push(instruction);
    }

    fn ld32(&mut self, destination: u8, base: u8, delta: u8, offset: u16) -> Result<()> {
        self.words
            .push(encode_ld32_m_immediate(destination, base, delta, offset)?);
        Ok(())
    }

    fn st32(&mut self, source: u8, base: u8, delta: u8, offset: u16) -> Result<()> {
        self.words
            .push(encode_st32_m_immediate(source, base, delta, offset)?);
        Ok(())
    }

    fn add_immediate(&mut self, destination: u8, source: u8, immediate: i32) -> Result<()> {
        self.words
            .push(encode_add_m_immediate(destination, source, immediate)?);
        Ok(())
    }

    fn put_special(&mut self, special: u8, register: u8) -> Result<()> {
        self.words.push(encode_put_special_m(special, register)?);
        Ok(())
    }

    fn call(&mut self, target: u32, return_register: u8) -> Result<()> {
        self.words
            .push(encode_call_m_immediate(return_register, target)?);
        Ok(())
    }

    fn brz(&mut self, register: u8, target: u32) -> Result<()> {
        self.words.push(encode_brz_m_immediate(register, target)?);
        Ok(())
    }

    fn jump(&mut self, target: u32) -> Result<()> {
        self.setzi(0, target)?;
        self.words.push(encode_br_m(0)?);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn symbols() -> BTreeMap<String, u32> {
        [
            (WORKER_BARRIER_SYMBOL.into(), 0x50000),
            (COMPLETE_SYMBOL.into(), 0x50004),
            (HOST_RUN_SYMBOL.into(), 0x50008),
            (REPEAT_CALL_SYMBOL.into(), 0x5000c),
            (SAMPLE_CYCLE_SYMBOL.into(), 0x50010),
            ("gemm".into(), 0x51000),
        ]
        .into_iter()
        .collect()
    }

    #[test]
    fn emits_resolved_exchange_and_compute_steps() {
        let mut row = vec![0; PLAN_WORDS];
        row[0] = SANS_INACTIVE_INSTRUCTION;
        let program = TileProgram {
            tile: 7,
            steps: vec![
                TileStep::Exchange(ExchangeStep {
                    address: 0x60000,
                    row,
                    profile: StepProfile::default(),
                }),
                TileStep::Compute(ComputeStep {
                    symbol: "gemm".into(),
                    output_address: 0x70000,
                    input_addresses: vec![0x71000, 0x72000],
                    arguments: vec![64],
                    profile: StepProfile::default(),
                }),
            ],
        };
        let generated = emit(
            &program,
            &symbols(),
            &HostProgram::default(),
            &CodegenOptions {
                code_address: 0x52000,
                ..CodegenOptions::default()
            },
        )
        .unwrap();
        assert!(!generated.bytes.is_empty());
        assert_eq!(generated.exchange_rows.len(), 1);
        assert_eq!(generated.exchange_rows[0].address, 0x60000);
    }

    #[test]
    fn rejects_unresolved_or_malformed_inputs() {
        let program = TileProgram {
            tile: 0,
            steps: vec![TileStep::Exchange(ExchangeStep {
                address: 3,
                row: Vec::new(),
                profile: StepProfile::default(),
            })],
        };
        assert!(matches!(
            emit(
                &program,
                &symbols(),
                &HostProgram::default(),
                &CodegenOptions::default()
            ),
            Err(CodegenError::Invalid(_))
        ));
    }
}
