[package]
name = "ipu-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ipu-trivial-test"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ipu-codegen = { path = "../ipu-codegen" }
ipu-driver = { path = "../ipu-driver" }
ipu-elf = { path = "../ipu-elf" }
ipu-exchange = { path = "../ipu-exchange" }
ipu-package = { path = "../ipu-package" }
ipu-runtime = { path = "../ipu-runtime" }
