[package]
name = "ipu-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ipu-trivial-test"
path = "src/main.rs"

[[bin]]
name = "ipu-exchange-schedule-bench"
path = "src/bin/exchange_schedule_bench.rs"

[[bin]]
name = "ipu-exchange-live-state"
path = "src/bin/exchange_live_state.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
ipu-codegen = { path = "../ipu-codegen" }
ipu-driver = { path = "../ipu-driver" }
ipu-elf = { path = "../ipu-elf" }
ipu-target = { path = "../ipu-target" }
ipu-package = { path = "../ipu-package" }
ipu-runtime = { path = "../ipu-runtime" }
fastrand.workspace = true
half.workspace = true
rand_distr.workspace = true
rand_xoshiro.workspace = true
serde_json.workspace = true
tracing.workspace = true
