[package]
name = "ipu-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ipu-stack"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
hex.workspace = true
ipu-driver = { path = "../ipu-driver" }
ipu-elf = { path = "../ipu-elf" }
ipu-package = { path = "../ipu-package" }
ipu-profile = { path = "../ipu-profile" }
ipu-runtime = { path = "../ipu-runtime" }
ipu-target = { path = "../ipu-target" }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
