[package]
name = "ipu-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ipu-exchange = { path = "../ipu-exchange" }
ipu-driver = { path = "../ipu-driver" }
ipu-elf = { path = "../ipu-elf" }
ipu-package = { path = "../ipu-package" }
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
fastrand.workspace = true
