//! Compare generated byte movement with an independent coordinate interpreter.
use super::*;
use crate::{
    AxisTiling, CoordinateMapping, GraphInputKind, MidInput, MidValue, Padding, TensorAxis,
    TensorShape, ValueId,
};

fn coordinates(mut index: u32, shape: &[u32]) -> Vec<u32> {
    let mut result = vec![0; shape.len()];
    for axis in (0..shape.len()).rev() {
        result[axis] = index % shape[axis];
        index /= shape[axis];
    }
    result
}

fn coordinate_value(
    mut point: Vec<u32>,
    shapes: &[TensorShape],
    mappings: &[CoordinateMapping],
) -> u32 {
    for index in (0..mappings.len()).rev() {
        let mapping = &mappings[index];
        for (axis, &offset) in mapping.offsets.iter().enumerate() {
            point[axis] += offset;
        }
        let source = &shapes[index].0;
        if let Some(view) = mapping.view {
            let mut extent = source.clone();
            let (split, merge) = if view.reversed {
                (view.merge_axis, view.split_axis)
            } else {
                (view.split_axis, view.merge_axis)
            };
            extent[split] /= view.factor;
            extent[merge] *= view.factor;
            if point.iter().zip(&extent).any(|(&p, &size)| p >= size) {
                return 0;
            }
            if view.reversed {
                let part = point[view.split_axis] / source[view.split_axis];
                point[view.split_axis] %= source[view.split_axis];
                point[view.merge_axis] = point[view.merge_axis] * view.factor + part;
            } else {
                point[view.split_axis] +=
                    point[view.merge_axis] % view.factor * (source[view.split_axis] / view.factor);
                point[view.merge_axis] /= view.factor;
            }
        }
        if point.iter().zip(source).any(|(&p, &size)| p >= size) {
            return 0;
        }
    }
    1000 + point
        .iter()
        .zip(&shapes[0].0)
        .fold(0, |index, (&p, &size)| index * size + p)
}

fn layout(random: &mut fastrand::Rng, shape: &TensorShape) -> Layout {
    match random.u8(0..4) {
        0 => Layout::row_major(TensorTiling::replicated(1 << random.u32(0..3))),
        1 => Layout::logical_linear(
            (1 << random.u32(0..3)).min((shape.elements() / 2) as u16),
            2,
        ),
        _ => {
            let axis = random.usize(0..shape.0.len());
            let replicas = 1 << random.u32(0..2);
            Layout::row_major(TensorTiling {
                tile_count: 2 * replicas,
                replicas,
                axes: vec![
                    AxisTiling::new(TensorAxis::FromStart(axis as u16), 2, 2, Padding::Zero)
                        .with_padding_multiple(if random.bool() { 4 } else { 2 })
                        .with_shard_padding_multiple(if random.bool() { 4 } else { 2 }),
                ],
            })
        }
    }
}

fn next_mapping(
    random: &mut fastrand::Rng,
    source: &TensorShape,
) -> (CoordinateMapping, TensorShape) {
    let rank = source.0.len();
    let split = random.usize(0..rank);
    let merge = (split + random.usize(1..rank)) % rank;
    let mut view = AxisFactorView::new(split, merge, 2);
    if random.bool() {
        view = view.inverse();
    }
    let divisible_axis = if view.reversed { merge } else { split };
    let view = (random.bool() && source.0[divisible_axis].is_multiple_of(4)).then_some(view);
    let mut output = view.map_or_else(|| source.clone(), |view| view.output_shape(source).unwrap());
    let offsets = output
        .0
        .iter_mut()
        .map(|size| {
            let offset = if *size >= 4 && random.bool() { 2 } else { 0 };
            *size -= offset;
            if *size >= 4 && random.bool() {
                *size -= 2;
            }
            if random.u8(0..4) == 0 {
                *size += 2;
            }
            offset
        })
        .collect();
    (CoordinateMapping { offsets, view }, output)
}

fn check_bytes(
    mid: &MidProgram,
    shapes: &[TensorShape],
    mappings: &[CoordinateMapping],
) -> Result<(), String> {
    let graph = expand_tiles(mid, false).map_err(|error| format!("expansion: {error:?}"))?;
    let low = crate::low::lower_to_tiles(&graph, false);
    let placement = crate::place(&low).map_err(|error| format!("placement: {error:?}"))?;
    let exchange = crate::exchange::capture_exchange_schedule(&low, &placement)
        .map_err(|error| format!("transfer lowering: {error:?}"))?;
    let mut memory = vec![vec![]; usize::from(mid.tile_count)];
    for shard in &low.shards {
        let Some(&address) = placement.shard_addresses.get(&shard.id) else {
            continue;
        };
        let words = ((address + shard_storage_bytes(shard).unwrap()) / 4) as usize;
        let data = &mut memory[usize::from(shard.tile)];
        data.resize(data.len().max(words), u32::MAX);
    }
    for &id in low.value_shards(low.inputs[0].value) {
        let shard = &low.shards[id.index() as usize];
        let widths = shard
            .extents
            .iter()
            .map(|e| e.physical_end - e.start)
            .collect::<Vec<_>>();
        for offset in 0..widths.iter().product::<u32>() {
            let point = coordinates(offset, &widths)
                .iter()
                .zip(&shard.extents)
                .map(|(&p, e)| p + e.start)
                .collect::<Vec<_>>();
            let value = if point
                .iter()
                .zip(&shard.extents)
                .all(|(&p, e)| p < e.logical_end)
            {
                coordinate_value(point, &shapes[..1], &[])
            } else {
                0
            };
            memory[usize::from(shard.tile)]
                [(placement.shard_addresses[&id] / 4 + offset) as usize] = value;
        }
    }
    for operation in &graph.body.operations {
        match operation {
            BlockOperation::Copy { tile, copy } => {
                let copy = &graph.local_copies[copy.0 as usize];
                let (rows, bytes, source_stride, destination_stride) = match copy.pattern {
                    CopyPattern::Contiguous => (1, copy.bytes, 0, 0),
                    CopyPattern::Strided {
                        rows,
                        row_bytes,
                        source_stride,
                        destination_stride,
                    } => (rows, row_bytes, source_stride, destination_stride),
                };
                for row in 0..rows {
                    let source = (placement.shard_addresses[&copy.source]
                        + copy.source_offset
                        + row * source_stride) as usize
                        / 4;
                    let destination = (placement.shard_addresses[&copy.destination]
                        + copy.destination_offset
                        + row * destination_stride) as usize
                        / 4;
                    let data = &mut memory[usize::from(*tile)];
                    data.copy_within(source..source + bytes as usize / 4, destination);
                }
            }
            BlockOperation::Exchange(phase) => {
                let phase = exchange
                    .phases
                    .iter()
                    .find(|candidate| candidate.phase == phase.index())
                    .unwrap();
                let messages = phase
                    .transfers
                    .iter()
                    .map(|transfer| {
                        let start = transfer.source_addresses[0] as usize / 4;
                        (
                            transfer,
                            memory[usize::from(transfer.source)]
                                [start..start + transfer.words as usize]
                                .to_vec(),
                        )
                    })
                    .collect::<Vec<_>>();
                for (transfer, payload) in messages {
                    for destination in &transfer.destinations {
                        let start = destination.address as usize / 4;
                        memory[usize::from(destination.tile)][start..start + payload.len()]
                            .copy_from_slice(&payload);
                    }
                }
            }
            BlockOperation::Compute { tile, run } => {
                let run = &graph.kernel_runs[run.0 as usize];
                let TileKernelSpec::FillZero { offset, bytes, .. } = run.kernel else {
                    return Err(format!("unexpected kernel {:?}", run.kernel));
                };
                let start =
                    (placement.shard_addresses[&run.outputs[0].shard] + offset) as usize / 4;
                memory[usize::from(*tile)][start..start + bytes as usize / 4].fill(0);
            }
            _ => return Err(format!("unexpected operation {operation:?}")),
        }
    }
    for &id in low.value_shards(low.outputs[0]) {
        let shard = &low.shards[id.index() as usize];
        let widths = shard
            .extents
            .iter()
            .map(|e| e.physical_end - e.start)
            .collect::<Vec<_>>();
        for offset in 0..widths.iter().product::<u32>() {
            let point = coordinates(offset, &widths)
                .iter()
                .zip(&shard.extents)
                .map(|(&p, e)| p + e.start)
                .collect::<Vec<_>>();
            let expected = if point
                .iter()
                .zip(&shard.extents)
                .all(|(&p, e)| p < e.logical_end)
            {
                coordinate_value(point.clone(), shapes, mappings)
            } else {
                0
            };
            let actual = memory[usize::from(shard.tile)]
                [(placement.shard_addresses[&id] / 4 + offset) as usize];
            if actual != expected {
                return Err(format!(
                    "tile {} coordinate {point:?}: got {actual}, expected {expected}",
                    shard.tile
                ));
            }
        }
    }
    Ok(())
}

#[test]
fn random_copy_chains_preserve_bytes_across_ownership_and_padding() {
    let mut random = fastrand::Rng::with_seed(0x636f_7079_6661_6374);
    for case in 0..256 {
        let rank = random.usize(2..=3);
        let mut shapes = vec![TensorShape(
            (0..rank).map(|_| 4 * random.u32(1..=3)).collect(),
        )];
        let mut mappings = vec![];
        for _ in 0..2 {
            let (mapping, shape) = next_mapping(&mut random, shapes.last().unwrap());
            mappings.push(mapping);
            shapes.push(shape);
        }
        let values = shapes
            .iter()
            .enumerate()
            .map(|(index, shape)| {
                let id = MidValueId::from_index(index as u32);
                MidValue {
                    id,
                    tensor_type: TensorType::new(
                        shape.0.clone(),
                        Precision::F32,
                        layout(&mut random, shape),
                    ),
                    origin: ValueId::from_index(index as u32),
                    storage_group: id,
                    tile_offset: random.u16(0..4),
                }
            })
            .collect();
        let mid = MidProgram {
            tile_count: 4,
            values,
            inputs: vec![MidInput {
                name: "input".into(),
                kind: GraphInputKind::Host,
                value: MidValueId::from_index(0),
            }],
            outputs: vec![MidValueId::from_index(2)],
            operations: mappings
                .iter()
                .enumerate()
                .map(|(index, mapping)| MidOperation {
                    source: None,
                    inputs: vec![MidValueId::from_index(index as u32)],
                    results: vec![MidValueId::from_index(index as u32 + 1)],
                    kind: MidOperationKind::Copy {
                        packing: crate::PackingPolicy::Automatic,
                        policy: match (case + index) % 3 {
                            0 => crate::CopyPolicy::Automatic,
                            1 if mapping.view.is_none() => crate::CopyPolicy::DirectRetile,
                            _ => crate::CopyPolicy::StageLogicalThenTransform,
                        },
                        mapping: mapping.clone(),
                        reuse_local: true,
                    },
                    estimated_cycles: 0,
                    estimated_exchange_cycles: 0,
                })
                .collect(),
            ..MidProgram::default()
        };
        for composed in [false, true] {
            let mut candidate = mid.clone();
            if composed {
                candidate.compose_copies();
            }
            if let Err(error) = check_bytes(&candidate, &shapes, &mappings) {
                panic!(
                    "case {case}, composed {composed}, {error}\nshapes {shapes:?}\nmappings {mappings:?}\nvalues {:?}",
                    mid.values
                );
            }
        }
    }
}

#[test]
fn forced_destination_packing_and_direct_transfers_preserve_the_same_values() {
    for shape in [[32, 64], [33, 66], [64, 128]] {
        let shapes = vec![TensorShape(shape.to_vec()); 3];
        let mappings = vec![CoordinateMapping::default(); 2];
        let mut sizes = vec![];
        for packing in [PackingPolicy::Direct, PackingPolicy::Staged] {
            let values = (0..3)
                .map(|index| {
                    let id = MidValueId::from_index(index);
                    MidValue {
                        id,
                        tensor_type: TensorType::new(
                            shape,
                            Precision::F32,
                            if index == 1 {
                                Layout::block_major_matrix(32, 1)
                            } else {
                                Layout::row_sharded(1)
                            },
                        ),
                        origin: ValueId::from_index(index),
                        storage_group: id,
                        tile_offset: index as u16,
                    }
                })
                .collect();
            let mut mid = MidProgram {
                tile_count: 3,
                values,
                inputs: vec![MidInput {
                    name: "input".into(),
                    kind: GraphInputKind::Host,
                    value: MidValueId::from_index(0),
                }],
                outputs: vec![MidValueId::from_index(2)],
                operations: (0..2)
                    .map(|index| MidOperation {
                        source: None,
                        inputs: vec![MidValueId::from_index(index)],
                        results: vec![MidValueId::from_index(index + 1)],
                        kind: MidOperationKind::Copy {
                            policy: CopyPolicy::StageLogicalThenTransform,
                            packing: if index == 0 {
                                packing
                            } else {
                                PackingPolicy::Automatic
                            },
                            mapping: CoordinateMapping::default(),
                            reuse_local: true,
                        },
                        estimated_cycles: 0,
                        estimated_exchange_cycles: 0,
                    })
                    .collect(),
                ..MidProgram::default()
            };
            mid.compose_copies();
            assert_eq!(
                mid.operations.len(),
                2,
                "preserve the explicitly selected packing site"
            );
            check_bytes(&mid, &shapes, &mappings)
                .unwrap_or_else(|error| panic!("{shape:?} {packing:?}: {error}"));
            sizes.push(expand_tiles(&mid, false).unwrap().shards.len());
            if packing == PackingPolicy::Direct {
                // Transposing individual halfwords cannot use this direct-word
                // realization. A forced request must not silently pick staging.
                for value in &mut mid.values {
                    value.tensor_type.format.precision = Precision::F16;
                }
                assert!(matches!(
                    expand_tiles(&mid, false),
                    Err(ExpansionError::InvalidCopyPlan)
                ));
            }
        }
        assert!(
            sizes[1] > sizes[0],
            "staged selection must declare its extra scratch"
        );
    }
}
